[package]
name = "chimney"
version = "0.2.3"
edition = "2021"
description = "A simple, fast and easy to use static file server."
authors = ["Ayodeji O. <ayodeji@trulyao.dev>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/aosasona/chimney"
repository = "https://github.com/aosasona/chimney"
keywords = ["static", "file", "server", "frontend", "web"]

[[bin]]
name = "chimney"
test = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.9.0"
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
futures-util = "0.3.31"
http-body-util = "0.1.2"
hyper = { version = "1.5.2", features = ["http1", "server"] }
hyper-util = { version = "0.1.10", features = ["tokio"] }
path-absolutize = "3.1.1"
pin-project-lite = "0.2.15"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = [
	"net",
	"macros",
	"rt-multi-thread",
	"io-util",
	"time",
	"fs",
	"signal",
] }
tokio-util = { version = "0.7.13", features = ["codec", "io"] }
toml = "0.8.19"
