[package]
name = "chimney"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
chrono = "0.4.34"
clap = { version = "4.5.0", features = ["derive"] }
futures-util = "0.3.30"
http-body-util = "0.1.0"
hyper = { version = "1.1.0", features = ["http1", "server"] }
hyper-util = { version = "0.1.3", features = ["tokio"] }
path-absolutize = "3.1.1"
pin-project-lite = "0.2.13"
serde = { version = "1.0.196", features = ["derive"] }
thiserror = "1.0.56"
tokio = { version = "1.36.0", features = ["net", "macros", "rt-multi-thread", "io-util", "time", "fs", "signal"] }
tokio-util = { version = "0.7.10", features = ["codec", "io"] }
toml = "0.8.10"
