host = "0.0.0.0"
port = 80
domain_names = [] # the domain names that the server will respond to
enable_logging = true # if true, the server will log all requests to the console
root_dir = "." # the directory where the server will look for files to serve, relative to where this config file is located unless an absolute path is provided
fallback_document = "index.html" # whenever a request doesn't match a file, the server will serve this file


# [https]
# enable = false # if true, the server will use HTTPS
# auto_redirect = true # if true, the server will redirect all HTTP requests to HTTPS
# port = 443
# use_self_signed = false # if true, the server will use a self-signed certificate for SSL

# or you can use your own certificate for production use cases

# cert_file = "" # if `local_cert` is false, this should be the path to the SSL certificate
# key_file = "" # if `local_cert` is false, this should be the path to the SSL key

# [rewrites]
# the leading slash is required, if it is not present, the server will NOT recognize the path
# "/home" = { to = "/index.html" } # if a request is made to /home, the server will serve /index.html instead
# "/page-2" = "another_page.html" # this is relative to the root directory, so if the root directory is `public`, the server will serve `public/another_page.html` instead

# [headers]
# these headers will be added to every response
# "Cache-Control" = "no-cache, no-store, must-revalidate"
# "Pragma" = "no-cache"

# [redirects]
# the leading slash is required, if it is not present, the server will NOT recognize the path
# "/rick" = "https://www.youtube.com/watch?v=dQw4w9WgXcQ" # if a request is made to /rick, the server will redirect to the Rick Astley video
# "/google" = { to = "https://google.com", replay = true } # replay here means that the server will ask the browser to replay the request to the new location (HTTP status 308)
