name: Build and publish archives
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  # Build tar archives for all supported platforms
  build-archives:
    name: Build archives
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

          - build: aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl

          - build: i686
            os: ubuntu-latest
            target: i686-unknown-linux-musl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build binaries
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --release --target ${{ matrix.target }}

      - name: Build archive
        shell: bash
        run: |
          name="chimney"
          dirname="$name-${{ env.VERSION }}-${{ matrix.target }}"

          mkdir "$dirname"

          mv "target/${{ matrix.target }}/release/$name" "$dirname"

          tar -czf "$dirname.tar.gz" "$dirname"
          echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV

      - name: Upload archives
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ASSET }}
          path: ${{ env.ASSET }}
