name: Build and publish archives
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  # Build tar archives for all supported platforms
  build-archives:
    name: Build archives
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

          - build: windows-gnu
            os: ubuntu-latest
            target: x86_64-pc-windows-gnu

          - build: aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl

          - build: i686
            os: ubuntu-latest
            target: i686-unknown-linux-musl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --release --target ${{ matrix.target }}

      - name: Build archive
        shell: bash
        run: |
          name="chimney"
          dirname="$name-${{ env.VERSION }}-${{ matrix.target }}"

          mkdir "$dirname"

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv "target/${{ matrix.target }}/release/$name.exe" "$dirname"
          else
            mv "target/${{ matrix.target }}/release/$name" "$dirname"
          fi

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a "$dirname.zip" "$dirname"
            echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          else
            tar -czf "$dirname.tar.gz" "$dirname"
            echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload the archives
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}
